// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `not_connected`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MoozeCore>>
abstract class MoozeCore implements RustOpaqueInterface {
  /// Bitcoin balance from local state.
  Future<BalanceDto> bitcoinBalance();

  /// Chain tip height.
  Future<int> bitcoinBlockHeight();

  /// Loads or creates the Bitcoin wallet for `mnemonic`.
  Future<void> bitcoinConnect({required String mnemonic});

  /// Drops the Bitcoin wallet. Idempotent.
  Future<void> bitcoinDisconnect();

  /// Fee estimate for a send.
  Future<FeeEstimateDto> bitcoinEstimateFee({required SendRequestDto request});

  /// Next unused receive address.
  Future<ReceiveAddressDto> bitcoinReceiveAddress({String? label});

  /// Adds a transaction broadcast elsewhere, for example a peg-in funding.
  Future<void> bitcoinRegisterExternalBroadcast({
    required TransactionDto transaction,
  });

  /// Builds, signs and broadcasts a send.
  Future<BroadcastResultDto> bitcoinSend({required SendRequestDto request});

  /// Syncs the Bitcoin wallet.
  Future<SyncOutcomeDto> bitcoinSync();

  /// Transaction changes since the last call.
  Future<List<TransactionEventDto>> bitcoinTakeEvents();

  /// Bitcoin transactions from local state, newest first.
  Future<List<TransactionDto>> bitcoinTransactions();

  /// Imports the snapshot from `FlutterDataExporter`, once.
  Future<MigrationReportDto> importFlutterSnapshot({
    required String snapshotJson,
  });

  /// True once the Flutter data import finished.
  Future<bool> isMigrated();

  /// Applies known per-asset deltas to the cached balance.
  Future<BalanceDto> liquidApplyBalanceDelta({
    required List<String> assetIds,
    required Int64List deltas,
  });

  /// Liquid balance from local state.
  Future<BalanceDto> liquidBalance();

  /// Builds an unsigned L-BTC send. A drain sends the whole L-BTC balance.
  Future<LiquidSendDraftDto> liquidBuildLbtcSend({
    required String destination,
    required BigInt amountSat,
    double? feeRateSatPerVb,
    required bool drain,
  });

  /// Loads or creates the Liquid wallet for `mnemonic`.
  Future<void> liquidConnect({required String mnemonic});

  /// Drops the Liquid wallet. Idempotent.
  Future<void> liquidDisconnect();

  /// Fee estimate for a send.
  Future<FeeEstimateDto> liquidEstimateFee({required SendRequestDto request});

  /// Receive address, optionally for one asset.
  Future<ReceiveAddressDto> liquidReceiveAddress({
    String? assetId,
    String? label,
  });

  /// Re-reads balances from the local wallet, no network.
  Future<BalanceDto> liquidRefreshBalance();

  /// Builds, signs and broadcasts a send.
  Future<BroadcastResultDto> liquidSend({
    required SendRequestDto request,
    required String mnemonic,
  });

  /// Signs a PSET with `mnemonic` and broadcasts it. Returns the txid.
  Future<String> liquidSignAndBroadcast({
    required String pset,
    required String mnemonic,
  });

  /// Signs a SideSwap swap PSET. Returns the signed PSET.
  Future<String> liquidSignSwapPset({
    required String pset,
    required String mnemonic,
  });

  /// Syncs the Liquid wallet.
  Future<SyncOutcomeDto> liquidSync();

  /// Transaction changes since the last call.
  Future<List<TransactionEventDto>> liquidTakeEvents();

  /// Liquid transactions from local state, newest first.
  Future<List<TransactionDto>> liquidTransactions();

  /// Unblinded UTXOs, for SideSwap.
  Future<List<LiquidUtxoDto>> liquidUtxos();

  /// Opens the core in `config.data_dir`.
  static Future<MoozeCore> open({required CoreConfig config}) =>
      MoozeCoreLib.instance.api.crateApiCoreMoozeCoreOpen(config: config);
}
