// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/mooze_app/dto/pix.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid`, `pix_service`

/// Time between `pixPollTick` calls, in ms.
int pixPollIntervalMs() =>
    MoozeCoreLib.instance.api.crateApiPixPixPollIntervalMs();

/// Fee breakdown for `amount_brl`. Pass the asset price in BRL to get the
/// estimated asset amount.
PixFeeDto pixFee({
  required double amountBrl,
  required bool hasReferral,
  double? quoteBrl,
}) => MoozeCoreLib.instance.api.crateApiPixPixFee(
  amountBrl: amountBrl,
  hasReferral: hasReferral,
  quoteBrl: quoteBrl,
);

/// Validates a deposit amount in BRL. Pass `None` while the limits load:
/// every positive amount is then valid, as in Dart.
DepositValidationDto pixValidateAmount({
  required double amountBrl,
  DepositLimitsDto? limits,
}) => MoozeCoreLib.instance.api.crateApiPixPixValidateAmount(
  amountBrl: amountBrl,
  limits: limits,
);

/// Validates a CPF (11 digits) or CNPJ (14 digits), masked or raw.
/// Returns `None` when valid.
CpfValidationErrorDto? taxIdValidate({required String input}) =>
    MoozeCoreLib.instance.api.crateApiPixTaxIdValidate(input: input);

/// True if `input` is a valid CPF or CNPJ.
bool taxIdIsValid({required String input}) =>
    MoozeCoreLib.instance.api.crateApiPixTaxIdIsValid(input: input);

/// Keeps only the digits.
String taxIdStrip({required String input}) =>
    MoozeCoreLib.instance.api.crateApiPixTaxIdStrip(input: input);

/// Formats digits as CPF (up to 11) or CNPJ (12 or more).
String taxIdFormat({required String digits}) =>
    MoozeCoreLib.instance.api.crateApiPixTaxIdFormat(digits: digits);

/// Live input mask (Dart `CpfCnpjInputFormatter`): strips, caps at 14
/// digits, formats.
String taxIdMaskInput({required String text}) =>
    MoozeCoreLib.instance.api.crateApiPixTaxIdMaskInput(text: text);

/// True if `value` looks like a PIX key or a BR Code payload
/// (Dart `PixKeyDetector`).
bool pixLooksLikeKey({required String value}) =>
    MoozeCoreLib.instance.api.crateApiPixPixLooksLikeKey(value: value);
