// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/mooze_app/dto/swap.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `not_connected`, `peg_core_error`, `peg_store`, `session`

/// Validates a peg amount (Dart `evaluatePegAmount`). The minimum comes
/// from `limits`, or `fallback_minimum_sats` when unknown. A drain is
/// always valid.
PegAmountValidationDto pegValidateAmount({
  required PegDirectionDto direction,
  BigInt? amountSat,
  required BigInt spendableSat,
  PegServerLimitsDto? limits,
  required BigInt fallbackMinimumSats,
  required bool drain,
}) => MoozeCoreLib.instance.api.crateApiSwapPegValidateAmount(
  direction: direction,
  amountSat: amountSat,
  spendableSat: spendableSat,
  limits: limits,
  fallbackMinimumSats: fallbackMinimumSats,
  drain: drain,
);

/// Default SideSwap endpoint.
String sideswapDefaultUrl() =>
    MoozeCoreLib.instance.api.crateApiSwapSideswapDefaultUrl();
