// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `balance`, `closed`, `disconnected`, `not_connected`, `peg_core_error`, `peg_store`, `quote`, `session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Validates a peg amount (Dart `evaluatePegAmount`). The minimum comes
/// from `limits`, or `fallback_minimum_sats` when unknown. A drain is
/// always valid.
PegAmountValidationDto pegValidateAmount({
  required PegDirectionDto direction,
  BigInt? amountSat,
  required BigInt spendableSat,
  PegServerLimitsDto? limits,
  required BigInt fallbackMinimumSats,
  required bool drain,
}) => MoozeCoreLib.instance.api.crateApiSwapPegValidateAmount(
  direction: direction,
  amountSat: amountSat,
  spendableSat: spendableSat,
  limits: limits,
  fallbackMinimumSats: fallbackMinimumSats,
  drain: drain,
);

/// Default SideSwap endpoint.
String sideswapDefaultUrl() =>
    MoozeCoreLib.instance.api.crateApiSwapSideswapDefaultUrl();

/// Why a peg amount cannot be used.
enum PegAmountIssueDto { belowMinimum, aboveBalance }

/// Result of `pegValidateAmount`.
class PegAmountValidationDto {
  /// False when no amount was entered.
  final bool hasAmount;
  final bool isValid;
  final PegAmountIssueDto? issue;
  final BigInt? minimumSats;
  final BigInt? maximumSats;

  /// True when the UI should show the issue.
  final bool showsIssue;

  const PegAmountValidationDto({
    required this.hasAmount,
    required this.isValid,
    this.issue,
    this.minimumSats,
    this.maximumSats,
    required this.showsIssue,
  });

  @override
  int get hashCode =>
      hasAmount.hashCode ^
      isValid.hashCode ^
      issue.hashCode ^
      minimumSats.hashCode ^
      maximumSats.hashCode ^
      showsIssue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegAmountValidationDto &&
          runtimeType == other.runtimeType &&
          hasAmount == other.hasAmount &&
          isValid == other.isValid &&
          issue == other.issue &&
          minimumSats == other.minimumSats &&
          maximumSats == other.maximumSats &&
          showsIssue == other.showsIssue;
}

/// Peg direction.
enum PegDirectionDto {
  /// BTC to L-BTC.
  pegIn,

  /// L-BTC to BTC.
  pegOut,
}

/// A funded peg.
class PegExecutionDto {
  final PegOrderDto order;
  final String fundingTxId;

  const PegExecutionDto({required this.order, required this.fundingTxId});

  @override
  int get hashCode => order.hashCode ^ fundingTxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegExecutionDto &&
          runtimeType == other.runtimeType &&
          order == other.order &&
          fundingTxId == other.fundingTxId;
}

/// A created peg order.
class PegOrderDto {
  final String orderId;
  final PegDirectionDto direction;

  /// SideSwap address the funding pays to.
  final String depositAddress;
  final String payoutAddress;
  final BigInt createdAtMs;
  final BigInt? expiresAtMs;

  const PegOrderDto({
    required this.orderId,
    required this.direction,
    required this.depositAddress,
    required this.payoutAddress,
    required this.createdAtMs,
    this.expiresAtMs,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      direction.hashCode ^
      depositAddress.hashCode ^
      payoutAddress.hashCode ^
      createdAtMs.hashCode ^
      expiresAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegOrderDto &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          direction == other.direction &&
          depositAddress == other.depositAddress &&
          payoutAddress == other.payoutAddress &&
          createdAtMs == other.createdAtMs &&
          expiresAtMs == other.expiresAtMs;
}

/// Phase of a peg.
enum PegPhaseDto {
  awaitingDeposit,
  detected,
  processing,
  completed,
  insufficientAmount,
  failed,
}

/// One-shot status of a peg order.
class PegProgressDto {
  final String orderId;
  final PegDirectionDto direction;
  final PegPhaseDto phase;
  final String depositAddress;
  final String payoutAddress;
  final BigInt totalDepositedSat;
  final BigInt totalPayoutSat;
  final String? payoutTxId;

  const PegProgressDto({
    required this.orderId,
    required this.direction,
    required this.phase,
    required this.depositAddress,
    required this.payoutAddress,
    required this.totalDepositedSat,
    required this.totalPayoutSat,
    this.payoutTxId,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      direction.hashCode ^
      phase.hashCode ^
      depositAddress.hashCode ^
      payoutAddress.hashCode ^
      totalDepositedSat.hashCode ^
      totalPayoutSat.hashCode ^
      payoutTxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegProgressDto &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          direction == other.direction &&
          phase == other.phase &&
          depositAddress == other.depositAddress &&
          payoutAddress == other.payoutAddress &&
          totalDepositedSat == other.totalDepositedSat &&
          totalPayoutSat == other.totalPayoutSat &&
          payoutTxId == other.payoutTxId;
}

/// Price of a peg before confirming.
class PegQuoteDto {
  final PegDirectionDto direction;
  final BigInt amountSat;
  final BigInt networkFeeSat;
  final BigInt serviceFeeSat;
  final BigInt minimumSat;
  final BigInt totalFeeSat;
  final BigInt estimatedReceiveSat;

  const PegQuoteDto({
    required this.direction,
    required this.amountSat,
    required this.networkFeeSat,
    required this.serviceFeeSat,
    required this.minimumSat,
    required this.totalFeeSat,
    required this.estimatedReceiveSat,
  });

  @override
  int get hashCode =>
      direction.hashCode ^
      amountSat.hashCode ^
      networkFeeSat.hashCode ^
      serviceFeeSat.hashCode ^
      minimumSat.hashCode ^
      totalFeeSat.hashCode ^
      estimatedReceiveSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegQuoteDto &&
          runtimeType == other.runtimeType &&
          direction == other.direction &&
          amountSat == other.amountSat &&
          networkFeeSat == other.networkFeeSat &&
          serviceFeeSat == other.serviceFeeSat &&
          minimumSat == other.minimumSat &&
          totalFeeSat == other.totalFeeSat &&
          estimatedReceiveSat == other.estimatedReceiveSat;
}

/// A stored peg (Dart `PegSwapEntry` row).
class PegRecordDto {
  final String orderId;
  final PegDirectionDto direction;
  final String sideswapAddress;
  final String payoutAddress;
  final BigInt amountSat;
  final BigInt createdAtMs;
  final String walletId;

  /// `pending`, `completed`, `failed` or `insufficient_amount`.
  final String status;
  final String? fundingTxId;
  final String? payoutTxId;
  final String? errorMessage;
  final BigInt? updatedAtMs;

  const PegRecordDto({
    required this.orderId,
    required this.direction,
    required this.sideswapAddress,
    required this.payoutAddress,
    required this.amountSat,
    required this.createdAtMs,
    required this.walletId,
    required this.status,
    this.fundingTxId,
    this.payoutTxId,
    this.errorMessage,
    this.updatedAtMs,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      direction.hashCode ^
      sideswapAddress.hashCode ^
      payoutAddress.hashCode ^
      amountSat.hashCode ^
      createdAtMs.hashCode ^
      walletId.hashCode ^
      status.hashCode ^
      fundingTxId.hashCode ^
      payoutTxId.hashCode ^
      errorMessage.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegRecordDto &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          direction == other.direction &&
          sideswapAddress == other.sideswapAddress &&
          payoutAddress == other.payoutAddress &&
          amountSat == other.amountSat &&
          createdAtMs == other.createdAtMs &&
          walletId == other.walletId &&
          status == other.status &&
          fundingTxId == other.fundingTxId &&
          payoutTxId == other.payoutTxId &&
          errorMessage == other.errorMessage &&
          updatedAtMs == other.updatedAtMs;
}

/// Result of `pegRefreshDue`.
class PegRefreshDto {
  /// Every tracked peg after the refresh.
  final List<TrackedPegDto> pegs;

  /// Order ids whose state changed.
  final List<String> changed;

  /// Pegs that reached a terminal phase in this refresh (persisted).
  final List<TrackedPegDto> finished;

  /// When to call `pegRefreshDue` again. `None`: nothing to poll.
  final BigInt? nextWakeupMs;

  const PegRefreshDto({
    required this.pegs,
    required this.changed,
    required this.finished,
    this.nextWakeupMs,
  });

  @override
  int get hashCode =>
      pegs.hashCode ^
      changed.hashCode ^
      finished.hashCode ^
      nextWakeupMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegRefreshDto &&
          runtimeType == other.runtimeType &&
          pegs == other.pegs &&
          changed == other.changed &&
          finished == other.finished &&
          nextWakeupMs == other.nextWakeupMs;
}

/// SideSwap peg minimums and fees (Dart `PegServerLimits`).
class PegServerLimitsDto {
  final BigInt minPegInSat;
  final BigInt minPegOutSat;
  final double serverFeePercentPegIn;
  final double serverFeePercentPegOut;

  const PegServerLimitsDto({
    required this.minPegInSat,
    required this.minPegOutSat,
    required this.serverFeePercentPegIn,
    required this.serverFeePercentPegOut,
  });

  @override
  int get hashCode =>
      minPegInSat.hashCode ^
      minPegOutSat.hashCode ^
      serverFeePercentPegIn.hashCode ^
      serverFeePercentPegOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegServerLimitsDto &&
          runtimeType == other.runtimeType &&
          minPegInSat == other.minPegInSat &&
          minPegOutSat == other.minPegOutSat &&
          serverFeePercentPegIn == other.serverFeePercentPegIn &&
          serverFeePercentPegOut == other.serverFeePercentPegOut;
}

/// One SideSwap quote emission (Dart `QuoteResponse`). Amounts in base units.
class QuoteDto {
  final QuoteStatusDto status;

  /// Set on success. Pass it to `sideswapExecuteSwap`.
  final BigInt? quoteId;
  final BigInt? baseAmount;
  final BigInt? quoteAmount;
  final BigInt? serverFee;
  final BigInt? fixedFee;

  /// Quote lifetime in ms. Set on success.
  final BigInt? ttlMs;

  /// Server balance. Set on low balance.
  final BigInt? available;

  /// Set on error.
  final String? errorMessage;
  final BigInt? quoteSubId;
  final BigInt? requestedAmount;
  final String? baseAssetId;
  final String? quoteAssetId;

  const QuoteDto({
    required this.status,
    this.quoteId,
    this.baseAmount,
    this.quoteAmount,
    this.serverFee,
    this.fixedFee,
    this.ttlMs,
    this.available,
    this.errorMessage,
    this.quoteSubId,
    this.requestedAmount,
    this.baseAssetId,
    this.quoteAssetId,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      quoteId.hashCode ^
      baseAmount.hashCode ^
      quoteAmount.hashCode ^
      serverFee.hashCode ^
      fixedFee.hashCode ^
      ttlMs.hashCode ^
      available.hashCode ^
      errorMessage.hashCode ^
      quoteSubId.hashCode ^
      requestedAmount.hashCode ^
      baseAssetId.hashCode ^
      quoteAssetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuoteDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          quoteId == other.quoteId &&
          baseAmount == other.baseAmount &&
          quoteAmount == other.quoteAmount &&
          serverFee == other.serverFee &&
          fixedFee == other.fixedFee &&
          ttlMs == other.ttlMs &&
          available == other.available &&
          errorMessage == other.errorMessage &&
          quoteSubId == other.quoteSubId &&
          requestedAmount == other.requestedAmount &&
          baseAssetId == other.baseAssetId &&
          quoteAssetId == other.quoteAssetId;
}

/// Status of one quote emission.
enum QuoteStatusDto { success, lowBalance, error }

/// One item of the `sideswapEvents` stream.
class SideSwapEventDto {
  final SideSwapEventKind kind;
  final QuoteDto? quote;
  final BigInt? balanceSat;
  final String? message;

  const SideSwapEventDto({
    required this.kind,
    this.quote,
    this.balanceSat,
    this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ quote.hashCode ^ balanceSat.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SideSwapEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          quote == other.quote &&
          balanceSat == other.balanceSat &&
          message == other.message;
}

/// Kind of a `sideswapEvents` item.
enum SideSwapEventKind {
  /// A quote for the active subscription, or a synthetic timeout error.
  quote,
  pegInWalletBalance,
  pegOutWalletBalance,

  /// The socket dropped. The driver reconnects with backoff; quotes must
  /// be started again.
  disconnected,

  /// Last item: the driver stopped (cancelled, or reconnects exhausted).
  closed,
}

/// A SideSwap asset.
class SideswapAssetDto {
  final String assetId;
  final String name;
  final String ticker;
  final int precision;
  final String? iconUrl;
  final bool? instantSwaps;

  const SideswapAssetDto({
    required this.assetId,
    required this.name,
    required this.ticker,
    required this.precision,
    this.iconUrl,
    this.instantSwaps,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      name.hashCode ^
      ticker.hashCode ^
      precision.hashCode ^
      iconUrl.hashCode ^
      instantSwaps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SideswapAssetDto &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          name == other.name &&
          ticker == other.ticker &&
          precision == other.precision &&
          iconUrl == other.iconUrl &&
          instantSwaps == other.instantSwaps;
}

/// A SideSwap market.
class SideswapMarketDto {
  final String baseAssetId;
  final String quoteAssetId;

  /// `Base` or `Quote`.
  final String feeAsset;
  final String marketType;

  const SideswapMarketDto({
    required this.baseAssetId,
    required this.quoteAssetId,
    required this.feeAsset,
    required this.marketType,
  });

  @override
  int get hashCode =>
      baseAssetId.hashCode ^
      quoteAssetId.hashCode ^
      feeAsset.hashCode ^
      marketType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SideswapMarketDto &&
          runtimeType == other.runtimeType &&
          baseAssetId == other.baseAssetId &&
          quoteAssetId == other.quoteAssetId &&
          feeAsset == other.feeAsset &&
          marketType == other.marketType;
}

/// Result of `sideswapStartQuote`.
class StartQuoteDto {
  /// False when another quote request still holds the lock.
  final bool started;
  final BigInt? quoteSubId;

  /// Market base asset. Differs from the send asset on an inverse market.
  final String? baseAssetId;
  final String? quoteAssetId;

  const StartQuoteDto({
    required this.started,
    this.quoteSubId,
    this.baseAssetId,
    this.quoteAssetId,
  });

  @override
  int get hashCode =>
      started.hashCode ^
      quoteSubId.hashCode ^
      baseAssetId.hashCode ^
      quoteAssetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartQuoteDto &&
          runtimeType == other.runtimeType &&
          started == other.started &&
          quoteSubId == other.quoteSubId &&
          baseAssetId == other.baseAssetId &&
          quoteAssetId == other.quoteAssetId;
}

/// A peg the tracker follows (Dart `TrackedPeg`).
class TrackedPegDto {
  final String orderId;
  final PegDirectionDto direction;
  final PegPhaseDto phase;
  final BigInt amountSat;
  final String depositAddress;
  final String? fundingTxId;
  final String? payoutTxId;
  final int? confirmations;
  final int? requiredConfirmations;
  final String? errorMessage;

  const TrackedPegDto({
    required this.orderId,
    required this.direction,
    required this.phase,
    required this.amountSat,
    required this.depositAddress,
    this.fundingTxId,
    this.payoutTxId,
    this.confirmations,
    this.requiredConfirmations,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      direction.hashCode ^
      phase.hashCode ^
      amountSat.hashCode ^
      depositAddress.hashCode ^
      fundingTxId.hashCode ^
      payoutTxId.hashCode ^
      confirmations.hashCode ^
      requiredConfirmations.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackedPegDto &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          direction == other.direction &&
          phase == other.phase &&
          amountSat == other.amountSat &&
          depositAddress == other.depositAddress &&
          fundingTxId == other.fundingTxId &&
          payoutTxId == other.payoutTxId &&
          confirmations == other.confirmations &&
          requiredConfirmations == other.requiredConfirmations &&
          errorMessage == other.errorMessage;
}
