// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_domain`, `to_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Derivation of an address the wallet owns.
class AddressOwnershipDto {
  final KeychainDto keychain;
  final int index;

  const AddressOwnershipDto({required this.keychain, required this.index});

  @override
  int get hashCode => keychain.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressOwnershipDto &&
          runtimeType == other.runtimeType &&
          keychain == other.keychain &&
          index == other.index;
}

/// Response of `MoozeCore.apiRequest`. Non-2xx statuses are not errors.
class ApiResponseDto {
  final int status;

  /// Body as UTF-8 text, lossy.
  final String body;

  const ApiResponseDto({required this.status, required this.body});

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResponseDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}

/// Balance of one asset.
class AssetBalanceDto {
  final ChainDto chain;
  final String? assetId;
  final BigInt amountSat;
  final int precision;
  final String? ticker;
  final BigInt pendingSat;

  const AssetBalanceDto({
    required this.chain,
    this.assetId,
    required this.amountSat,
    required this.precision,
    this.ticker,
    required this.pendingSat,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      assetId.hashCode ^
      amountSat.hashCode ^
      precision.hashCode ^
      ticker.hashCode ^
      pendingSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetBalanceDto &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          assetId == other.assetId &&
          amountSat == other.amountSat &&
          precision == other.precision &&
          ticker == other.ticker &&
          pendingSat == other.pendingSat;
}

/// Outcome of the boot-time session check.
class AuthEnsureDto {
  final AuthEnsureKind kind;

  /// The 5xx status for `ApiDown`, if the error text holds one.
  final int? statusCode;

  /// Error text for `Failed`.
  final String? message;

  const AuthEnsureDto({required this.kind, this.statusCode, this.message});

  @override
  int get hashCode => kind.hashCode ^ statusCode.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthEnsureDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          statusCode == other.statusCode &&
          message == other.message;
}

/// Result of `MoozeCore.authEnsureSession`. Mirrors the flags of the Dart
/// `ensureAuthSessionProvider`.
enum AuthEnsureKind {
  /// A valid session exists.
  ready,

  /// The secure store holds no mnemonic, so the core cannot sign in.
  missingMnemonic,

  /// The backend looks down (Dart `apiDownProvider`).
  apiDown,

  /// Any other failure (Dart `syncErrorMessageProvider`).
  failed,
}

/// Protocol used to reach the chains.
enum BackendDto { esplora, electrum }

/// Snapshot of all balances of one wallet.
class BalanceDto {
  final List<AssetBalanceDto> assets;
  final BigInt snapshotAtMs;

  const BalanceDto({required this.assets, required this.snapshotAtMs});

  @override
  int get hashCode => assets.hashCode ^ snapshotAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BalanceDto &&
          runtimeType == other.runtimeType &&
          assets == other.assets &&
          snapshotAtMs == other.snapshotAtMs;
}

/// Result of a broadcast.
class BroadcastResultDto {
  final ChainDto chain;
  final String txId;
  final TransactionDto transaction;
  final BigInt? feePaidSat;

  const BroadcastResultDto({
    required this.chain,
    required this.txId,
    required this.transaction,
    this.feePaidSat,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      txId.hashCode ^
      transaction.hashCode ^
      feePaidSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BroadcastResultDto &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          txId == other.txId &&
          transaction == other.transaction &&
          feePaidSat == other.feePaidSat;
}

/// Chain of a balance or transaction.
enum ChainDto { liquid, bitcoin, lightning, aggregate }

/// Settings for [`super::core::MoozeCore::open`].
class CoreConfig {
  /// Directory the core may own. The app support directory is a good choice.
  final String dataDir;
  final NetworkDto network;
  final BackendDto backend;

  /// Custom Bitcoin node. Empty uses the default servers.
  final String bitcoinNodeUrl;

  /// Custom Liquid node. Empty uses the default servers.
  final String liquidNodeUrl;

  const CoreConfig({
    required this.dataDir,
    required this.network,
    required this.backend,
    required this.bitcoinNodeUrl,
    required this.liquidNodeUrl,
  });

  @override
  int get hashCode =>
      dataDir.hashCode ^
      network.hashCode ^
      backend.hashCode ^
      bitcoinNodeUrl.hashCode ^
      liquidNodeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          network == other.network &&
          backend == other.backend &&
          bitcoinNodeUrl == other.bitcoinNodeUrl &&
          liquidNodeUrl == other.liquidNodeUrl;
}

/// Error thrown on the Dart side by every failing bridge call.
class CoreError implements FrbException {
  final CoreErrorKind kind;
  final String message;

  const CoreError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Category of a bridge error. Dart maps it to its failure classes.
enum CoreErrorKind {
  service,
  storage,
  credential,
  network,
  invalidInput,
  invalidState,
  timeout,
  other,

  /// The API session is missing or could not be refreshed.
  session,
}

/// One derived wallet address.
class DerivedAddressDto {
  final KeychainDto keychain;
  final int index;

  /// Address the UI shows. Liquid: the confidential address.
  final String address;

  /// Liquid: the unconfidential address. Bitcoin: `None`.
  final String? unconfidential;

  /// Hex of the script pubkey.
  final String scriptHex;

  /// True if a wallet transaction ever paid to the address.
  final bool used;

  const DerivedAddressDto({
    required this.keychain,
    required this.index,
    required this.address,
    this.unconfidential,
    required this.scriptHex,
    required this.used,
  });

  @override
  int get hashCode =>
      keychain.hashCode ^
      index.hashCode ^
      address.hashCode ^
      unconfidential.hashCode ^
      scriptHex.hashCode ^
      used.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedAddressDto &&
          runtimeType == other.runtimeType &&
          keychain == other.keychain &&
          index == other.index &&
          address == other.address &&
          unconfidential == other.unconfidential &&
          scriptHex == other.scriptHex &&
          used == other.used;
}

/// Device metrics the API client adds to JSON request bodies
/// (Dart `AuthInterceptor._collectMetrics`).
class DeviceMetricsDto {
  /// Value of `MoozeCore.authDeviceId`.
  final String deviceId;

  /// Battery level, 0 to 100.
  final PlatformInt64? batteryLevel;

  /// Screen brightness, 0.0 to 1.0.
  final double? screenBrightness;

  /// Boot time as an ISO-8601 string.
  final String? bootTime;

  const DeviceMetricsDto({
    required this.deviceId,
    this.batteryLevel,
    this.screenBrightness,
    this.bootTime,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      batteryLevel.hashCode ^
      screenBrightness.hashCode ^
      bootTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceMetricsDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          batteryLevel == other.batteryLevel &&
          screenBrightness == other.screenBrightness &&
          bootTime == other.bootTime;
}

/// Transaction direction.
enum DirectionDto { incoming, outgoing, internal, selfTransfer, swap }

/// Fee estimate for one send.
class FeeEstimateDto {
  final ChainDto chain;
  final FeePriorityDto priority;
  final BigInt absoluteFeeSat;
  final double? feeRateSatPerVbyte;
  final int? estimatedBlocks;

  const FeeEstimateDto({
    required this.chain,
    required this.priority,
    required this.absoluteFeeSat,
    this.feeRateSatPerVbyte,
    this.estimatedBlocks,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      priority.hashCode ^
      absoluteFeeSat.hashCode ^
      feeRateSatPerVbyte.hashCode ^
      estimatedBlocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeEstimateDto &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          priority == other.priority &&
          absoluteFeeSat == other.absoluteFeeSat &&
          feeRateSatPerVbyte == other.feeRateSatPerVbyte &&
          estimatedBlocks == other.estimatedBlocks;
}

/// Fee priority.
enum FeePriorityDto { low, medium, high }

/// HTTP method of `MoozeCore.apiRequest`.
enum HttpMethodDto { get_, post, put, patch, delete }

/// Keychain of a derived address.
enum KeychainDto {
  /// Receive chain.
  external_,

  /// Change chain.
  internal,
}

/// Unsigned L-BTC send, ready for review and signing.
class LiquidSendDraftDto {
  final String pset;
  final String destination;
  final BigInt amountSat;
  final BigInt feeSat;
  final double feeRateSatPerKvb;
  final bool drain;

  const LiquidSendDraftDto({
    required this.pset,
    required this.destination,
    required this.amountSat,
    required this.feeSat,
    required this.feeRateSatPerKvb,
    required this.drain,
  });

  @override
  int get hashCode =>
      pset.hashCode ^
      destination.hashCode ^
      amountSat.hashCode ^
      feeSat.hashCode ^
      feeRateSatPerKvb.hashCode ^
      drain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiquidSendDraftDto &&
          runtimeType == other.runtimeType &&
          pset == other.pset &&
          destination == other.destination &&
          amountSat == other.amountSat &&
          feeSat == other.feeSat &&
          feeRateSatPerKvb == other.feeRateSatPerKvb &&
          drain == other.drain;
}

/// Unblinded Liquid output.
class LiquidUtxoDto {
  final String txid;
  final int vout;
  final String assetId;
  final String assetBlindingFactor;
  final BigInt valueSat;
  final String valueBlindingFactor;

  const LiquidUtxoDto({
    required this.txid,
    required this.vout,
    required this.assetId,
    required this.assetBlindingFactor,
    required this.valueSat,
    required this.valueBlindingFactor,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      assetId.hashCode ^
      assetBlindingFactor.hashCode ^
      valueSat.hashCode ^
      valueBlindingFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiquidUtxoDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          assetId == other.assetId &&
          assetBlindingFactor == other.assetBlindingFactor &&
          valueSat == other.valueSat &&
          valueBlindingFactor == other.valueBlindingFactor;
}

/// Result of the one-time data import.
class MigrationReportDto {
  final bool alreadyDone;
  final List<TableCountDto> copied;
  final List<SkippedRowDto> skipped;

  const MigrationReportDto({
    required this.alreadyDone,
    required this.copied,
    required this.skipped,
  });

  @override
  int get hashCode => alreadyDone.hashCode ^ copied.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationReportDto &&
          runtimeType == other.runtimeType &&
          alreadyDone == other.alreadyDone &&
          copied == other.copied &&
          skipped == other.skipped;
}

/// Network the wallet runs on.
enum NetworkDto { mainnet, testnet, regtest }

/// Next receive address with its index.
class NextUnusedAddressDto {
  final int index;

  /// Address the UI shows. Liquid: the confidential address.
  final String address;

  /// True if a wallet transaction already paid to it. Bitcoin: always false.
  final bool used;

  const NextUnusedAddressDto({
    required this.index,
    required this.address,
    required this.used,
  });

  @override
  int get hashCode => index.hashCode ^ address.hashCode ^ used.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NextUnusedAddressDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          address == other.address &&
          used == other.used;
}

/// Address or invoice to receive funds.
class ReceiveAddressDto {
  final ChainDto chain;
  final String? address;
  final String? assetId;
  final String? label;
  final BigInt? amountSat;

  const ReceiveAddressDto({
    required this.chain,
    this.address,
    this.assetId,
    this.label,
    this.amountSat,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      address.hashCode ^
      assetId.hashCode ^
      label.hashCode ^
      amountSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveAddressDto &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          address == other.address &&
          assetId == other.assetId &&
          label == other.label &&
          amountSat == other.amountSat;
}

/// Request to send on-chain. The chain follows from the method called.
class SendRequestDto {
  final String destination;
  final BigInt amountSat;
  final String? assetId;
  final FeePriorityDto feePriority;
  final String? label;
  final bool subtractFeeFromAmount;
  final double? feeRateOverrideSatPerVbyte;
  final bool drain;

  const SendRequestDto({
    required this.destination,
    required this.amountSat,
    this.assetId,
    required this.feePriority,
    this.label,
    required this.subtractFeeFromAmount,
    this.feeRateOverrideSatPerVbyte,
    required this.drain,
  });

  @override
  int get hashCode =>
      destination.hashCode ^
      amountSat.hashCode ^
      assetId.hashCode ^
      feePriority.hashCode ^
      label.hashCode ^
      subtractFeeFromAmount.hashCode ^
      feeRateOverrideSatPerVbyte.hashCode ^
      drain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendRequestDto &&
          runtimeType == other.runtimeType &&
          destination == other.destination &&
          amountSat == other.amountSat &&
          assetId == other.assetId &&
          feePriority == other.feePriority &&
          label == other.label &&
          subtractFeeFromAmount == other.subtractFeeFromAmount &&
          feeRateOverrideSatPerVbyte == other.feeRateOverrideSatPerVbyte &&
          drain == other.drain;
}

/// A row the import left out.
class SkippedRowDto {
  final String table;
  final String key;
  final String reason;

  const SkippedRowDto({
    required this.table,
    required this.key,
    required this.reason,
  });

  @override
  int get hashCode => table.hashCode ^ key.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkippedRowDto &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          key == other.key &&
          reason == other.reason;
}

/// Backend that produced a transaction record.
enum SourceDto { lwk, breez, bdk }

/// Transaction status.
enum StatusDto { pending, confirmed, failed }

/// Result of one sync.
class SyncOutcomeDto {
  final ChainDto chain;
  final int fetched;
  final int changed;
  final BigInt durationMs;

  const SyncOutcomeDto({
    required this.chain,
    required this.fetched,
    required this.changed,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      fetched.hashCode ^
      changed.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncOutcomeDto &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          fetched == other.fetched &&
          changed == other.changed &&
          durationMs == other.durationMs;
}

/// Rows copied from one source table.
class TableCountDto {
  final String table;
  final int count;

  const TableCountDto({required this.table, required this.count});

  @override
  int get hashCode => table.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableCountDto &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          count == other.count;
}

/// One wallet transaction.
class TransactionDto {
  final String id;
  final ChainDto chain;
  final DirectionDto direction;
  final StatusDto status;
  final PlatformInt64 amountSat;
  final PlatformInt64 feeSat;
  final BigInt timestampMs;
  final int confirmations;
  final String? assetId;
  final String? address;
  final String? label;
  final String? fromAssetId;
  final String? toAssetId;
  final PlatformInt64? sentAmountSat;
  final PlatformInt64? receivedAmountSat;
  final SourceDto? source;
  final String? swapLockupTxId;
  final String? swapClaimTxId;

  const TransactionDto({
    required this.id,
    required this.chain,
    required this.direction,
    required this.status,
    required this.amountSat,
    required this.feeSat,
    required this.timestampMs,
    required this.confirmations,
    this.assetId,
    this.address,
    this.label,
    this.fromAssetId,
    this.toAssetId,
    this.sentAmountSat,
    this.receivedAmountSat,
    this.source,
    this.swapLockupTxId,
    this.swapClaimTxId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      chain.hashCode ^
      direction.hashCode ^
      status.hashCode ^
      amountSat.hashCode ^
      feeSat.hashCode ^
      timestampMs.hashCode ^
      confirmations.hashCode ^
      assetId.hashCode ^
      address.hashCode ^
      label.hashCode ^
      fromAssetId.hashCode ^
      toAssetId.hashCode ^
      sentAmountSat.hashCode ^
      receivedAmountSat.hashCode ^
      source.hashCode ^
      swapLockupTxId.hashCode ^
      swapClaimTxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          chain == other.chain &&
          direction == other.direction &&
          status == other.status &&
          amountSat == other.amountSat &&
          feeSat == other.feeSat &&
          timestampMs == other.timestampMs &&
          confirmations == other.confirmations &&
          assetId == other.assetId &&
          address == other.address &&
          label == other.label &&
          fromAssetId == other.fromAssetId &&
          toAssetId == other.toAssetId &&
          sentAmountSat == other.sentAmountSat &&
          receivedAmountSat == other.receivedAmountSat &&
          source == other.source &&
          swapLockupTxId == other.swapLockupTxId &&
          swapClaimTxId == other.swapClaimTxId;
}

/// A transaction appeared or changed.
class TransactionEventDto {
  final TransactionEventKindDto kind;
  final TransactionDto transaction;
  final BigInt observedAtMs;
  final StatusDto? previousStatus;
  final int? previousConfirmations;

  const TransactionEventDto({
    required this.kind,
    required this.transaction,
    required this.observedAtMs,
    this.previousStatus,
    this.previousConfirmations,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      transaction.hashCode ^
      observedAtMs.hashCode ^
      previousStatus.hashCode ^
      previousConfirmations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          transaction == other.transaction &&
          observedAtMs == other.observedAtMs &&
          previousStatus == other.previousStatus &&
          previousConfirmations == other.previousConfirmations;
}

/// Kind of transaction change found by a sync.
enum TransactionEventKindDto { created, statusChanged, confirmationsChanged }

/// One unspent wallet output.
class WalletUtxoDto {
  final String txid;
  final int vout;

  /// Address of the output. Liquid: the confidential address.
  final String address;

  /// Liquid: the unconfidential address. Bitcoin: `None`.
  final String? unconfidential;

  /// Hex of the script pubkey.
  final String scriptHex;
  final KeychainDto keychain;
  final int index;

  /// Value in sats (Bitcoin) or asset base units (Liquid).
  final BigInt amountSat;

  /// Liquid asset id. Bitcoin: `None`.
  final String? assetId;

  /// Height of the confirming block. `None` while unconfirmed.
  final int? confirmationHeight;

  /// Block time (seconds) of the confirming block, if known.
  final BigInt? confirmationTimeS;

  const WalletUtxoDto({
    required this.txid,
    required this.vout,
    required this.address,
    this.unconfidential,
    required this.scriptHex,
    required this.keychain,
    required this.index,
    required this.amountSat,
    this.assetId,
    this.confirmationHeight,
    this.confirmationTimeS,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      address.hashCode ^
      unconfidential.hashCode ^
      scriptHex.hashCode ^
      keychain.hashCode ^
      index.hashCode ^
      amountSat.hashCode ^
      assetId.hashCode ^
      confirmationHeight.hashCode ^
      confirmationTimeS.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletUtxoDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          address == other.address &&
          unconfidential == other.unconfidential &&
          scriptHex == other.scriptHex &&
          keychain == other.keychain &&
          index == other.index &&
          amountSat == other.amountSat &&
          assetId == other.assetId &&
          confirmationHeight == other.confirmationHeight &&
          confirmationTimeS == other.confirmationTimeS;
}
