// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/mooze_app/dto/config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Settings for [`super::core::MoozeCore::open`].
class CoreConfig {
  /// Directory the core may own. The app support directory is a good choice.
  final String dataDir;
  final NetworkDto network;
  final BackendDto backend;

  /// Custom Bitcoin node. Empty uses the default servers.
  final String bitcoinNodeUrl;

  /// Custom Liquid node. Empty uses the default servers.
  final String liquidNodeUrl;

  const CoreConfig({
    required this.dataDir,
    required this.network,
    required this.backend,
    required this.bitcoinNodeUrl,
    required this.liquidNodeUrl,
  });

  @override
  int get hashCode =>
      dataDir.hashCode ^
      network.hashCode ^
      backend.hashCode ^
      bitcoinNodeUrl.hashCode ^
      liquidNodeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          network == other.network &&
          backend == other.backend &&
          bitcoinNodeUrl == other.bitcoinNodeUrl &&
          liquidNodeUrl == other.liquidNodeUrl;
}

/// Error thrown on the Dart side by every failing bridge call.
class CoreError implements FrbException {
  final CoreErrorKind kind;
  final String message;

  const CoreError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Category of a bridge error. Dart maps it to its failure classes.
enum CoreErrorKind {
  service,
  storage,
  credential,
  network,
  invalidInput,
  invalidState,
  timeout,
  other,

  /// The API session is missing or could not be refreshed.
  session,
}
