use mooze_app::dto::{BalanceDto, SyncStateDto, TransactionDto, HoldingDto};
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub enum WalletChain {
    Bitcoin,
    Liquid,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SessionDto {
    pub status: String,
    pub generation: u32,
    pub retry_after_ms: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct HostInfoDto {
    pub network: String,
    pub backend: String,
    pub liquid_policy_asset: String,
    pub bitcoin_endpoints: Vec<String>,
    pub liquid_endpoints: Vec<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ReviewRequestDto {
    pub chain: WalletChain,
    pub destination: String,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub amount_sat: u64,
    pub fee_rate_sat_per_vbyte: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SendReviewDto {
    pub id: String,
    pub request: ReviewRequestDto,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub fee_sat: u64,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub total_sat: u64,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub expires_at_ms: u64,
    pub generation: u32,
}
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct DesktopSnapshotDto {
    pub submission: Option<SubmissionDto>,
    pub bitcoin: BalanceDto,
    pub liquid: BalanceDto,
    pub transactions: Vec<TransactionDto>,
    pub sync: Option<SyncStateDto>,
    pub chains: Vec<ChainStateDto>,
    pub generation: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ChainStateDto {
    pub chain: WalletChain,
    pub phase: String,
    #[cfg_attr(feature = "codegen", ts(type = "number | null"))]
    pub last_success_at_ms: Option<u64>,
    pub error: Option<String>,
}

#[cfg(feature = "codegen")]
pub fn generated_types() -> String {
    use ts_rs::{Config, TS};
    let mut out=String::from("// Generated by desktop codegen. Do not edit.\nimport type { BalanceDto, TransactionDto, SyncStateDto, HoldingDto } from '../../../../crates/mooze-app/generated/types';\n");
    let config = Config::default();
    macro_rules! export {($($t:ty),*)=>{$(out.push_str("export ");out.push_str(&<$t>::decl(&config));out.push('\n');)*};}
    export!(
        HoldingsSnapshotDto,
        WalletChain,
        SessionDto,
        HostInfoDto,
        ReviewRequestDto,
        SendReviewDto,
        ChainStateDto,
        DesktopSnapshotDto,
        SubmissionDto
    );
    out
}
#[cfg(all(test, feature = "codegen"))]
mod codegen_test {
    #[test]
    fn bindings_are_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../frontend/src/core/desktop.generated.ts");
        assert_eq!(
            std::fs::read_to_string(path).unwrap(),
            super::generated_types()
        );
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SubmissionDto {
    pub phase: String,
    pub chain: WalletChain,
    pub tx_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature="codegen", derive(ts_rs::TS))]
pub struct HoldingsSnapshotDto { pub generation: u32, pub holdings: Vec<HoldingDto>, pub chains: Vec<ChainStateDto> }
