pub use crate::service_dto::*;
use mooze_app::dto::{AssetAmountDto, AssetKeyDto, HoldingDto, SyncStateDto, WalletActivityDto};
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub enum WalletChain {
    Bitcoin,
    Liquid,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SessionDto {
    pub status: String,
    pub generation: u32,
    pub retry_after_ms: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct HostInfoDto {
    pub pix_enabled: bool,
    pub swaps_enabled: bool,
    pub network: String,
    pub backend: String,
    pub liquid_policy_asset: String,
    pub bitcoin_endpoints: Vec<String>,
    pub liquid_endpoints: Vec<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ReviewRequestDto {
    pub asset: AssetKeyDto,
    pub destination: String,
    pub amount: SendAmountDto,
    pub fee_rate_sat_per_vbyte: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
#[serde(tag = "mode", content = "units")]
pub enum SendAmountDto {
    Exact(String),
    Max,
}
impl ReviewRequestDto {
    pub fn chain(&self) -> WalletChain {
        if self.asset.chain == mooze_app::dto::ChainDto::Bitcoin {
            WalletChain::Bitcoin
        } else {
            WalletChain::Liquid
        }
    }
    pub fn exact_amount(&self) -> Option<u64> {
        match &self.amount {
            SendAmountDto::Exact(v) if !v.is_empty() && v.bytes().all(|b| b.is_ascii_digit()) => {
                v.parse::<u64>().ok().filter(|v| *v > 0)
            }
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SendReviewDto {
    pub is_max: bool,
    pub id: String,
    pub request: ReviewRequestDto,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub fee_sat: u64,
    pub debits: Vec<AssetAmountDto>,
    #[cfg_attr(feature = "codegen", ts(type = "number"))]
    pub expires_at_ms: u64,
    pub generation: u32,
}
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct DesktopSnapshotDto {
    pub submission: Option<SubmissionDto>,
    pub activity: Vec<WalletActivityDto>,
    pub sync: Option<SyncStateDto>,
    pub chains: Vec<ChainStateDto>,
    pub generation: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ChainStateDto {
    pub chain: WalletChain,
    pub phase: String,
    #[cfg_attr(feature = "codegen", ts(type = "number | null"))]
    pub last_success_at_ms: Option<u64>,
    pub error: Option<String>,
}

#[cfg(feature = "codegen")]
pub fn generated_types() -> String {
    use ts_rs::{Config, TS};
    let mut out=String::from("// Generated by desktop codegen. Do not edit.\nimport type { BalanceDto, TransactionDto, SyncStateDto, HoldingDto, AssetKeyDto, AssetAmountDto, WalletActivityDto } from '../../../../crates/mooze-app/generated/types';\n");
    let config = Config::new().with_large_int("number");
    macro_rules! export {($($t:ty),*)=>{$(out.push_str("export ");out.push_str(&<$t>::decl(&config));out.push('\n');)*};}
    export!(
        AccountTierDto,
        AccountLevelDto,
        PriceMarketDto,
        PricePointDto,
        PriceHistoryDto,
        SwapRequestDto,
        SwapReviewDto,
        SwapStateDto,
        BackendSessionDto,
        PixCreateRequestDto,
        PixDepositViewDto,
        PixHistoryDto,
        SendAmountDto,
        ParsedPaymentDto,
        ReceiveRequestDto,
        FeeOptionsDto,
        SetupDto,
        DesktopSettingsDto,
        HoldingsSnapshotDto,
        WalletChain,
        SessionDto,
        HostInfoDto,
        ReviewRequestDto,
        SendReviewDto,
        ChainStateDto,
        DesktopSnapshotDto,
        SubmissionDto
    );
    out
}
#[cfg(all(test, feature = "codegen"))]
mod codegen_test {
    #[test]
    fn bindings_are_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../frontend/src/core/desktop.generated.ts");
        assert_eq!(
            std::fs::read_to_string(path).unwrap(),
            super::generated_types()
        );
    }
}

fn legacy_submission_version() -> u32 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SubmissionDto {
    #[serde(default = "legacy_submission_version")]
    pub version: u32,
    #[serde(default)]
    pub request: Option<ReviewRequestDto>,
    #[serde(default)]
    pub debits: Option<Vec<AssetAmountDto>>,
    pub phase: String,
    pub chain: WalletChain,
    pub tx_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct HoldingsSnapshotDto {
    pub generation: u32,
    pub holdings: Vec<HoldingDto>,
    pub chains: Vec<ChainStateDto>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct DesktopSettingsDto {
    pub version: u32,
    pub lock_minutes: u16,
    pub locale: String,
    pub bitcoin_unit: String,
    pub privacy: bool,
    pub bitcoin_node: Option<String>,
    pub liquid_node: Option<String>,
    pub public_fallback: bool,
}
impl Default for DesktopSettingsDto {
    fn default() -> Self {
        Self {
            version: 1,
            lock_minutes: 1,
            locale: "pt-BR".into(),
            bitcoin_unit: "BTC".into(),
            privacy: false,
            bitcoin_node: None,
            liquid_node: None,
            public_fallback: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct SetupDto {
    pub setup_id: String,
    pub words: Vec<String>,
    pub challenge_indices: Vec<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ParsedPaymentDto {
    pub chain: WalletChain,
    pub address: String,
    pub asset: Option<AssetKeyDto>,
    pub amount_units: Option<String>,
    pub description: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct ReceiveRequestDto {
    pub address: String,
    pub uri: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "codegen", derive(ts_rs::TS))]
pub struct FeeOptionsDto {
    pub kind: String,
    pub source: String,
    pub observed_at_ms: u64,
    pub rates: Vec<f64>,
}

#[cfg(test)]
mod submission_tests {
    #[test]
    fn legacy_submission_keeps_unknown_details_unknown() {
        let old = r#"{"phase":"submitting","chain":"Bitcoin","tx_id":null}"#;
        let state: super::SubmissionDto = serde_json::from_str(old).unwrap();
        assert_eq!(state.version, 1);
        assert!(state.request.is_none());
        assert!(state.debits.is_none());
    }
}
