// Generated by desktop codegen. Do not edit.
import type { BalanceDto, TransactionDto, SyncStateDto } from '../../../../crates/mooze-app/generated/types';
export type WalletChain = "Bitcoin" | "Liquid";
export type SessionDto = { status: string, generation: number, retry_after_ms: number, };
export type HostInfoDto = { network: string, backend: string, liquid_policy_asset: string, bitcoin_endpoints: Array<string>, liquid_endpoints: Array<string>, };
export type ReviewRequestDto = { chain: WalletChain, destination: string, amount_sat: number, fee_rate_sat_per_vbyte: number, };
export type SendReviewDto = { id: string, request: ReviewRequestDto, fee_sat: number, total_sat: number, expires_at_ms: number, generation: number, };
export type ChainStateDto = { chain: WalletChain, phase: string, last_success_at_ms: number | null, error: string | null, };
export type DesktopSnapshotDto = { submission: SubmissionDto | null, bitcoin: BalanceDto, liquid: BalanceDto, transactions: Array<TransactionDto>, sync: SyncStateDto | null, chains: Array<ChainStateDto>, generation: number, };
export type SubmissionDto = { phase: string, chain: WalletChain, tx_id: string | null, };
