// Generated by desktop codegen. Do not edit.
import type { BalanceDto, TransactionDto, SyncStateDto, HoldingDto, AssetKeyDto, AssetAmountDto, WalletActivityDto } from '../../../../crates/mooze-app/generated/types';
export type SendAmountDto = { "mode": "Exact", "units": string } | { "mode": "Max" };
export type ParsedPaymentDto = { chain: WalletChain, address: string, asset: AssetKeyDto | null, amount_units: string | null, description: string | null, };
export type ReceiveRequestDto = { address: string, uri: string, };
export type FeeOptionsDto = { kind: string, source: string, observed_at_ms: number, rates: Array<number>, };
export type SetupDto = { setup_id: string, words: Array<string>, challenge_indices: Array<number>, };
export type DesktopSettingsDto = { version: number, lock_minutes: number, locale: string, bitcoin_unit: string, privacy: boolean, bitcoin_node: string | null, liquid_node: string | null, public_fallback: boolean, };
export type HoldingsSnapshotDto = { generation: number, holdings: Array<HoldingDto>, chains: Array<ChainStateDto>, };
export type WalletChain = "Bitcoin" | "Liquid";
export type SessionDto = { status: string, generation: number, retry_after_ms: number, };
export type HostInfoDto = { network: string, backend: string, liquid_policy_asset: string, bitcoin_endpoints: Array<string>, liquid_endpoints: Array<string>, };
export type ReviewRequestDto = { asset: AssetKeyDto, destination: string, amount: SendAmountDto, fee_rate_sat_per_vbyte: number, };
export type SendReviewDto = { is_max: boolean, id: string, request: ReviewRequestDto, fee_sat: number, debits: Array<AssetAmountDto>, expires_at_ms: number, generation: number, };
export type ChainStateDto = { chain: WalletChain, phase: string, last_success_at_ms: number | null, error: string | null, };
export type DesktopSnapshotDto = { submission: SubmissionDto | null, activity: Array<WalletActivityDto>, sync: SyncStateDto | null, chains: Array<ChainStateDto>, generation: number, };
export type SubmissionDto = { version: number, request: ReviewRequestDto | null, debits: Array<AssetAmountDto> | null, phase: string, chain: WalletChain, tx_id: string | null, };
