/// Dart bindings for mooze-core, generated by flutter_rust_bridge.
///
/// Call [MoozeCoreLib.init] once before any other call, then open the core
/// with [MoozeCore.open].
library;

export 'src/rust/api/core.dart';
export 'src/rust/api/pix.dart';
export 'src/rust/api/swap.dart';
export 'src/rust/api/types.dart';
export 'src/rust/frb_generated.dart' show MoozeCoreLib;
