import { vi } from "vitest";
import type { DesktopClient } from "../core/client";
export function fakeClient(): DesktopClient {
  return {
    swapMarkets: vi.fn(async () => []),
    swapStart: vi.fn(),
    swapStatus: vi.fn(async () => ({
      phase: "Idle",
      review: null,
      txid: null,
      message: null,
    })),
    swapStop: vi.fn(async () => {}),
    swapConfirm: vi.fn(),
    swapAcknowledge: vi.fn(),
    backendStatus: vi.fn(async () => ({ state: "Ready", retryable: false })),
    backendRetry: vi.fn(async () => ({ state: "Ready", retryable: false })),
    pixHistory: vi.fn(async () => ({
      deposits: [],
      creation_uncertain: false,
    })),
    pixCreate: vi.fn(),
    pixAcknowledgeUncertain: vi.fn(),
    removeWallet: vi.fn(),
    diagnostics: vi.fn(),
    exportDiagnostics: vi.fn(),
    testNode: vi.fn(),
    saveNode: vi.fn(),
    saveDisplay: vi.fn(),
    parsePaymentRequest: vi.fn(),
    receiveRequest: vi.fn(),
    feeOptions: vi.fn(async () => ({
      kind: "unavailable",
      source: "node",
      observed_at_ms: 0,
      rates: [],
    })),
    beginSetup: vi.fn(),
    cancelSetup: vi.fn(async () => {}),
    completeSetup: vi.fn(),
    revealRecoveryPhrase: vi.fn(),
    changePin: vi.fn(),
    recordActivity: vi.fn(async () => {}),
    settings: vi.fn(),
    setLockMinutes: vi.fn(),
    holdings: vi.fn(),
    approvedAssets: vi.fn(async () => [
      {
        key: { chain: "Bitcoin" as const, asset_id: null },
        ticker: "BTC",
        precision: 8,
        approved: true,
      },
    ]),
    hostInfo: vi.fn(),
    sessionStatus: vi.fn(),
    importWallet: vi.fn(),
    unlock: vi.fn(),
    lock: vi.fn(),
    snapshot: vi.fn(),
    refresh: vi.fn(),
    receiveAddress: vi.fn(),
    reviewSend: vi.fn(),
    acknowledgeSubmission: vi.fn(),
    confirmSend: vi.fn(),
    subscribe: vi.fn(),
  };
}
