// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class MoozeCoreLibApiImplPlatform
    extends BaseApiImpl<MoozeCoreLibWire> {
  MoozeCoreLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MoozeCorePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCorePtr;

  @protected
  MoozeCore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    dynamic raw,
  );

  @protected
  MoozeCore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    dynamic raw,
  );

  @protected
  MoozeCore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AssetBalanceDto dco_decode_asset_balance_dto(dynamic raw);

  @protected
  BackendDto dco_decode_backend_dto(dynamic raw);

  @protected
  BalanceDto dco_decode_balance_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CoreConfig dco_decode_box_autoadd_core_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SendRequestDto dco_decode_box_autoadd_send_request_dto(dynamic raw);

  @protected
  SourceDto dco_decode_box_autoadd_source_dto(dynamic raw);

  @protected
  StatusDto dco_decode_box_autoadd_status_dto(dynamic raw);

  @protected
  TransactionDto dco_decode_box_autoadd_transaction_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BroadcastResultDto dco_decode_broadcast_result_dto(dynamic raw);

  @protected
  ChainDto dco_decode_chain_dto(dynamic raw);

  @protected
  CoreConfig dco_decode_core_config(dynamic raw);

  @protected
  CoreError dco_decode_core_error(dynamic raw);

  @protected
  CoreErrorKind dco_decode_core_error_kind(dynamic raw);

  @protected
  DirectionDto dco_decode_direction_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeeEstimateDto dco_decode_fee_estimate_dto(dynamic raw);

  @protected
  FeePriorityDto dco_decode_fee_priority_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LiquidSendDraftDto dco_decode_liquid_send_draft_dto(dynamic raw);

  @protected
  LiquidUtxoDto dco_decode_liquid_utxo_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AssetBalanceDto> dco_decode_list_asset_balance_dto(dynamic raw);

  @protected
  List<LiquidUtxoDto> dco_decode_list_liquid_utxo_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SkippedRowDto> dco_decode_list_skipped_row_dto(dynamic raw);

  @protected
  List<TableCountDto> dco_decode_list_table_count_dto(dynamic raw);

  @protected
  List<TransactionDto> dco_decode_list_transaction_dto(dynamic raw);

  @protected
  List<TransactionEventDto> dco_decode_list_transaction_event_dto(dynamic raw);

  @protected
  MigrationReportDto dco_decode_migration_report_dto(dynamic raw);

  @protected
  NetworkDto dco_decode_network_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SourceDto? dco_decode_opt_box_autoadd_source_dto(dynamic raw);

  @protected
  StatusDto? dco_decode_opt_box_autoadd_status_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ReceiveAddressDto dco_decode_receive_address_dto(dynamic raw);

  @protected
  SendRequestDto dco_decode_send_request_dto(dynamic raw);

  @protected
  SkippedRowDto dco_decode_skipped_row_dto(dynamic raw);

  @protected
  SourceDto dco_decode_source_dto(dynamic raw);

  @protected
  StatusDto dco_decode_status_dto(dynamic raw);

  @protected
  SyncOutcomeDto dco_decode_sync_outcome_dto(dynamic raw);

  @protected
  TableCountDto dco_decode_table_count_dto(dynamic raw);

  @protected
  TransactionDto dco_decode_transaction_dto(dynamic raw);

  @protected
  TransactionEventDto dco_decode_transaction_event_dto(dynamic raw);

  @protected
  TransactionEventKindDto dco_decode_transaction_event_kind_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  MoozeCore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    SseDeserializer deserializer,
  );

  @protected
  MoozeCore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    SseDeserializer deserializer,
  );

  @protected
  MoozeCore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AssetBalanceDto sse_decode_asset_balance_dto(SseDeserializer deserializer);

  @protected
  BackendDto sse_decode_backend_dto(SseDeserializer deserializer);

  @protected
  BalanceDto sse_decode_balance_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_box_autoadd_core_config(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SendRequestDto sse_decode_box_autoadd_send_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceDto sse_decode_box_autoadd_source_dto(SseDeserializer deserializer);

  @protected
  StatusDto sse_decode_box_autoadd_status_dto(SseDeserializer deserializer);

  @protected
  TransactionDto sse_decode_box_autoadd_transaction_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BroadcastResultDto sse_decode_broadcast_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChainDto sse_decode_chain_dto(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_core_config(SseDeserializer deserializer);

  @protected
  CoreError sse_decode_core_error(SseDeserializer deserializer);

  @protected
  CoreErrorKind sse_decode_core_error_kind(SseDeserializer deserializer);

  @protected
  DirectionDto sse_decode_direction_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeeEstimateDto sse_decode_fee_estimate_dto(SseDeserializer deserializer);

  @protected
  FeePriorityDto sse_decode_fee_priority_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LiquidSendDraftDto sse_decode_liquid_send_draft_dto(
    SseDeserializer deserializer,
  );

  @protected
  LiquidUtxoDto sse_decode_liquid_utxo_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AssetBalanceDto> sse_decode_list_asset_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LiquidUtxoDto> sse_decode_list_liquid_utxo_dto(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SkippedRowDto> sse_decode_list_skipped_row_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TableCountDto> sse_decode_list_table_count_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionDto> sse_decode_list_transaction_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionEventDto> sse_decode_list_transaction_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  MigrationReportDto sse_decode_migration_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  NetworkDto sse_decode_network_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SourceDto? sse_decode_opt_box_autoadd_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  StatusDto? sse_decode_opt_box_autoadd_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ReceiveAddressDto sse_decode_receive_address_dto(
    SseDeserializer deserializer,
  );

  @protected
  SendRequestDto sse_decode_send_request_dto(SseDeserializer deserializer);

  @protected
  SkippedRowDto sse_decode_skipped_row_dto(SseDeserializer deserializer);

  @protected
  SourceDto sse_decode_source_dto(SseDeserializer deserializer);

  @protected
  StatusDto sse_decode_status_dto(SseDeserializer deserializer);

  @protected
  SyncOutcomeDto sse_decode_sync_outcome_dto(SseDeserializer deserializer);

  @protected
  TableCountDto sse_decode_table_count_dto(SseDeserializer deserializer);

  @protected
  TransactionDto sse_decode_transaction_dto(SseDeserializer deserializer);

  @protected
  TransactionEventDto sse_decode_transaction_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransactionEventKindDto sse_decode_transaction_event_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    MoozeCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    MoozeCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    MoozeCore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_asset_balance_dto(
    AssetBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backend_dto(BackendDto self, SseSerializer serializer);

  @protected
  void sse_encode_balance_dto(BalanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_core_config(
    CoreConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_send_request_dto(
    SendRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_dto(
    SourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_status_dto(
    StatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transaction_dto(
    TransactionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_broadcast_result_dto(
    BroadcastResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chain_dto(ChainDto self, SseSerializer serializer);

  @protected
  void sse_encode_core_config(CoreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_core_error(CoreError self, SseSerializer serializer);

  @protected
  void sse_encode_core_error_kind(CoreErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_direction_dto(DirectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee_estimate_dto(
    FeeEstimateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fee_priority_dto(
    FeePriorityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_liquid_send_draft_dto(
    LiquidSendDraftDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_liquid_utxo_dto(LiquidUtxoDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_balance_dto(
    List<AssetBalanceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_liquid_utxo_dto(
    List<LiquidUtxoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skipped_row_dto(
    List<SkippedRowDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_count_dto(
    List<TableCountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_dto(
    List<TransactionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_event_dto(
    List<TransactionEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_migration_report_dto(
    MigrationReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_dto(NetworkDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_source_dto(
    SourceDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_status_dto(
    StatusDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_receive_address_dto(
    ReceiveAddressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_request_dto(
    SendRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skipped_row_dto(SkippedRowDto self, SseSerializer serializer);

  @protected
  void sse_encode_source_dto(SourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_status_dto(StatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_outcome_dto(
    SyncOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_table_count_dto(TableCountDto self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_dto(
    TransactionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_event_dto(
    TransactionEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_event_kind_dto(
    TransactionEventKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class MoozeCoreLibWire implements BaseWire {
  factory MoozeCoreLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      MoozeCoreLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MoozeCoreLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_mooze_core_bridge_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_mooze_core_bridge_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCore =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoozeCorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
